name: viowet-ai-dev

services:
  postgres:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
